#' Forest plot summarizing Cox PH regression analysis results
#'
#' Forest plot summarizing Cox PH regression analysis results (univariable or multivariable models)
#' using tumor subtypes of density quartiles, across different param settings e.g. detection rates for feature selection
#' or batch_size/ max_batch/ no_of_random_merging in \code{meta_cluster}
#' @param root_dir A file.path pointing to the parent directory of the folders containing
#' results of multiple runs using different setting (to be examined)
#' @param param_bnm A character string of the key name for identifying the folder names of
#' the experimental setting of interest
#' @param pheno_dir_path A character string of the directory path to the (final) phenotype folder
#' @param  Cox_result_folderNm A character string of the directory path to the folder containing Cox PH output
#' results generated by \code{density_surv_analysis}
#' @param uni_fnm A character string used to search for the univariable Cox PH results
#' (as filename prefix) output by \code{density_surv_analysis}
#' @param multi_fnm A character string used to search for the multivariable Cox PH results
#' (as filename prefix) output by \code{density_surv_analysis}
#' @param output_dir A file.path string of output directory
#' @return PDF files containing forest plot
#' @import dplyr ggplot2
#' @export
Viz_foresPlot_denQ_CoxPH   <- function(root_dir=NULL, output_dir= root_dir,
                                    pheno_dir_path=NULL,
                                    Cox_result_folderNm='density_surv/cat',
                                    uni_fnm = 'uniCoxPH_', multi_fnm = 'multiCoxPH_',
                                   param_bnm = NULL){

  head <- NULL

  ############################################
  #### gather all HR & CI
  ############################################
  all_runs_uni <- NULL
  all_runs_multi <- NULL

  setwd(root_dir)
  folder_nms <- list.files(pattern = param_bnm)

  for(ff in folder_nms){
    if(!dir.exists((file.path(root_dir,ff,pheno_dir_path,Cox_result_folderNm))))next
    setwd(file.path(root_dir,ff,pheno_dir_path,Cox_result_folderNm))
    cat(ff, '\n')
    var <- gsub(x=ff, pattern = param_bnm, replacement = '')
    ## ===============
    ## univariable
    ## ===============
    uni_fnms <- list.files()
    uni_fnms <- grep(x=uni_fnms, pattern = uni_fnm, value = TRUE)
    uni_fnms <- grep(x=uni_fnms, pattern = '_HR_CI.RData', value = TRUE)
    uni_fnms <- grep(x=uni_fnms, pattern = '_S_|_T_', value = TRUE)

    data_uni <- NULL
    Q1 <- data.frame(HR=1, lower_CI=1, upper_CI=1, cat='Q1')
    for (cc in uni_fnms){

      cat(cc, '\n')
      setwd(file.path(root_dir,ff,pheno_dir_path,Cox_result_folderNm))
      #setwd(file.path(input_dir,ff,Cox_result_folderNm))
      tmp <- get(load(file=cc))

      tmp <- as.data.frame(tmp[[1]])
      tmp <- tmp[, c("exp(coef)","lower .95","upper .95")]
      colnames(tmp) <- plyr::mapvalues(x=colnames(tmp), from = c("exp(coef)","lower .95","upper .95"),
                                       to = c('HR','lower_CI','upper_CI'))

      tmp$cat <- sapply(strsplit(x=rownames(tmp), split = 'Q'),'[[', 2)
      tmp$cat <- paste0('Q',tmp$cat)
      rownames(tmp) <- NULL
      if(nrow(tmp)==0){
        tmp <- rbind(Q1,Q1,Q1,Q1)
        tmp$cat <- paste0('Q',c(1:4))
      }else{
        for(qq in paste0('Q',c(1:4))){
          #cat(qq,'\n')
          if(sum(tmp$cat %in% qq)==0){
            QX <- Q1
            QX$cat <- qq
            tmp <- rbind(tmp, QX)
          }
        } #tmp <- rbind(tmp, Q1)
      }
      tmp$area <- sapply(strsplit(x=cc, split = '_'),'[[', 3)

      tmp$model <- 'univariable'
      tmp$phenotype <- sapply(strsplit(x=cc, split = '_'),'[[', 2)

      data_uni <- rbind(data_uni, tmp)
    }#end folder_nms
    head(data_uni)
    table(data_uni[,c("phenotype",'cat')])

    data_uni[,param_bnm] <- var
    all_runs_uni <- rbind(all_runs_uni, data_uni)
    ## ===============
    ## multivariable
    ## ===============
    multi_fnms <- list.files()
    multi_fnms <- grep(x=multi_fnms, pattern = multi_fnm, value = TRUE)
    multi_fnms <- grep(x=multi_fnms, pattern = '_HR_CI.RData', value = TRUE)
    multi_fnms <- grep(x=multi_fnms, pattern = '_S_|_T_', value = TRUE)

    data_multi <- NULL
    Q1 <- data.frame(HR=1, lower_CI=1, upper_CI=1, cat='Q1')
    for (cc in multi_fnms){

      cat(cc, '\n')
      #setwd(file.path(input_dir,ff,Cox_result_folderNm))
      setwd(file.path(root_dir,ff,pheno_dir_path,Cox_result_folderNm))
      tmp <- get(load(file=cc))

      tmp <- as.data.frame(tmp[[1]])
      tmp <- tmp[, c("exp(coef)","lower .95","upper .95")]
      colnames(tmp) <- plyr::mapvalues(x=colnames(tmp), from = c("exp(coef)","lower .95","upper .95"),
                                       to = c('HR','lower_CI','upper_CI'))

      tmp <- tmp[grep(x=rownames(tmp), pattern = 'Q'),]
      tmp$cat <- sapply(strsplit(x=rownames(tmp), split = 'Q'),'[[', 2)
      tmp$cat <- paste0('Q',tmp$cat)
      rownames(tmp) <- NULL
      if(nrow(tmp)==0){
        tmp <- rbind(Q1,Q1,Q1,Q1)
        tmp$cat <- paste0('Q',c(1:4))
      }else{
        for(qq in paste0('Q',c(1:4))){
          #cat(qq,'\n')
          if(sum(tmp$cat %in% qq)==0){
            QX <- Q1
            QX$cat <- qq
            tmp <- rbind(tmp, QX)
          }
        } #tmp <- rbind(tmp, Q1)
      }
      tmp$area <- sapply(strsplit(x=cc, split = '_'),'[[', 3)

      tmp$model <- 'multivariable'
      tmp$phenotype <- sapply(strsplit(x=cc, split = '_'),'[[', 2)

      data_multi <- rbind(data_multi, tmp)
    }#end folder_nms
    head(data_multi)
    table(data_multi[,c("phenotype",'cat')])

    data_multi[,param_bnm] <- var
    all_runs_multi <- rbind(all_runs_multi, data_multi)

  }#end all no_random_merging folder_nms
  HR_CI <- rbind(all_runs_uni, all_runs_multi)
  save(HR_CI,
       file=file.path(output_dir, paste0('uni_multi_HR_CI.RData')))

  ############################################
  #### make forest plots
  ############################################
  forest_plot(HR_CI=HR_CI, output_dir= output_dir,
              param_bnm = param_bnm,tissue_areas = c('S', 'T'))

}
